export { app, auth, db } from './config';
export {
  onAuthChange,
  registerParent,
  loginParent,
  signOut,
  getFamilyDoc,
  verifyChildPin,
} from './auth';
export {
  updateFamilySettings,
  updateFamily,
  subscribeToFamily,
  incrementFamilyField,
  createTask,
  updateTask,
  deleteTask,
  subscribeTasks,
  createPeriod,
  updatePeriod,
  subscribePeriods,
  getActivePeriod,
  createCompletion,
  updateCompletion,
  subscribeCompletions,
  getCompletionsForDate,
  createReward,
  updateReward,
  deleteReward,
  subscribeRewards,
  createRedemption,
  updateRedemption,
  subscribeRedemptions,
  createGoal,
  updateGoal,
  deleteGoal,
  subscribeGoals,
  createEarnedBadge,
  subscribeEarnedBadges,
  createStreakFreeze,
  subscribeStreakFreezes,
} from './firestore';
