import { vi } from 'vitest';
export const createTask = vi.fn().mockResolvedValue('mock-task-id');
export const updateTask = vi.fn().mockResolvedValue(undefined);
export const deleteTask = vi.fn().mockResolvedValue(undefined);
export const subscribeTasks = vi.fn((familyId: string, cb: Function) => { cb([]); return vi.fn(); });
export const createPeriod = vi.fn().mockResolvedValue('mock-period-id');
export const updatePeriod = vi.fn().mockResolvedValue(undefined);
export const subscribePeriods = vi.fn((familyId: string, cb: Function) => { cb([]); return vi.fn(); });
export const getActivePeriod = vi.fn().mockResolvedValue(null);
export const createCompletion = vi.fn().mockResolvedValue(undefined);
export const updateCompletion = vi.fn().mockResolvedValue(undefined);
export const subscribeCompletions = vi.fn((familyId: string, periodId: string, cb: Function) => { cb([]); return vi.fn(); });
export const getCompletionsForDate = vi.fn().mockResolvedValue([]);
export const createReward = vi.fn().mockResolvedValue('mock-reward-id');
export const updateReward = vi.fn().mockResolvedValue(undefined);
export const deleteReward = vi.fn().mockResolvedValue(undefined);
export const subscribeRewards = vi.fn((familyId: string, cb: Function) => { cb([]); return vi.fn(); });
export const createRedemption = vi.fn().mockResolvedValue('mock-redemption-id');
export const updateRedemption = vi.fn().mockResolvedValue(undefined);
export const subscribeRedemptions = vi.fn((familyId: string, cb: Function) => { cb([]); return vi.fn(); });
export const updateFamilySettings = vi.fn().mockResolvedValue(undefined);
export const updateFamily = vi.fn().mockResolvedValue(undefined);
export const incrementFamilyField = vi.fn().mockResolvedValue(undefined);
export const subscribeToFamily = vi.fn((familyId: string, cb: Function) => { cb(null); return vi.fn(); });
export const stripUndefined = <T extends Record<string, any>>(obj: T): T =>
  Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== undefined)) as T;
